{{- if .Values.restart.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paragon-restart-manager-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: paragon-restart-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: paragon-restart-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}