apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prometheus.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "prometheus.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prometheus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            # Environment variable to let prometheus know we're running in k8s and that k8s service discovery
            # should be enabled
            - name: PLATFORM
              value: k8s
            {{- /* Handle environment variables */}}
            {{- if and .Values.envKeys (kindIs "slice" .Values.envKeys) }}
            {{- range $key := .Values.envKeys }}
            {{- if and $.Values.env (kindIs "map" $.Values.env) (hasKey $.Values.env $key) }}
            - name: {{ $key }}
              value: {{ index $.Values.env $key | quote }}
            {{- else if and $.Values.global.env (kindIs "map" $.Values.global.env) (hasKey $.Values.global.env $key) }}
            - name: {{ $key }}
              value: {{ index $.Values.global.env $key | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- /* Handle secrets */}}
            {{- if and .Values.secretKeys (kindIs "slice" .Values.secretKeys) }}
            {{- range $key := .Values.secretKeys }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{- if and $.Values.secrets (kindIs "map" $.Values.secrets) (hasKey $.Values.secrets $key) }}
                         {{ $.Values.secretName }}-{{ $.Chart.Name }}
                       {{- else }}
                         {{ $.Values.secretName }}
                       {{- end }}
                  key: {{ $key }}
                  optional: true
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: prometheus
              mountPath: /usr/src/app/data
          livenessProbe:
            httpGet:
              path: "/-/healthy"
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/-/ready"
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: prometheus
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        {{- if eq .Values.global.env.HOST_ENV "AWS_K8" }}
        storageClassName: gp3
        {{- end }}
