{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.secretName }}-{{ $.Chart.Name }}
  labels:
    {{- include "connect.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }} 
